const AUTHENTICATION_SET = 'AUTHENTICATION_SET';
const AUTHENTICATION_UNSET = 'AUTHENTICATION_UNSET';
const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export default {
  AUTHENTICATION_SET,
  AUTHENTICATION_UNSET,
  AUTHENTICATION_ERROR
}