const SET_CLIENT = 'SET_CLIENT';
const ADD_CLIENT = 'ADD_CLIENT';
const UPDATE_CLIENT = 'ADD_CLIENT';
const PERSIST_SUCCESS = 'PERSIST_SUCCESS_CLIENT';
const PERSIST_ERROR = 'PERSIST_ERROR_CLIENT';
const EDIT_REFRESH = 'EDIT_REFRESH_CLIENT';
const LIST = 'LIST_CLIENT';
const ERROR = 'ERROR_CLIENT';

export default {
  SET_CLIENT,
  ADD_CLIENT,
  UPDATE_CLIENT,
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  EDIT_REFRESH,
  LIST,
  ERROR
}