const SET_USER = 'SET_USER';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'ADD_USER';
const PERSIST_SUCCESS = 'PERSIST_SUCCESS';
const PERSIST_ERROR = 'PERSIST_ERROR';
const EDIT_REFRESH = 'EDIT_REFRESH';
const TOGGLE_USER = 'TOGGLE_USER';
const LIST = 'LIST_USERS';
const LIST_NOTES = 'LIST_NOTES';
const ADD_NOTE = 'ADD_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';
const DELETE_NOTE = 'DELETE_NOTE'

export default {
  SET_USER,
  ADD_USER,
  UPDATE_USER,
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  EDIT_REFRESH,
  TOGGLE_USER,
  LIST,
  LIST_NOTES,
  ADD_NOTE,
  UPDATE_NOTE,
  DELETE_NOTE
};
