const GET_USER = 'GET_USER';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'ADD_USER';
const PERSIST_SUCCESS = 'PERSIST_SUCCESS';
const PERSIST_ERROR = 'PERSIST_ERROR';
const EDIT_REFRESH = 'EDIT_REFRESH';
const TOGGLE_USER = 'TOGGLE_USER';
const LIST = 'LIST_USERS';

export default {
  GET_USER,
  ADD_USER,
  UPDATE_USER,
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  EDIT_REFRESH,
  TOGGLE_USER,
  LIST
};
