const PERSIST_SUCCESS = 'PERSIST_SUCCESS';
const PERSIST_ERROR = 'PERSIST_ERROR';
const LIST_NOTES = 'LIST_NOTES';
const ADD_NOTE = 'ADD_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const ERROR = 'ERROR';

export default {
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  LIST_NOTES,
  ADD_NOTE,
  UPDATE_NOTE,
  DELETE_NOTE,
  ERROR
};