const SET_SHIPPER = 'SET_SHIPPER';
const ADD_SHIPPER = 'ADD_SHIPPER';
const UPDATE_SHIPPER = 'ADD_SHIPPER';
const PERSIST_SUCCESS = 'PERSIST_SUCCESS';
const PERSIST_ERROR = 'PERSIST_ERROR';
const EDIT_REFRESH = 'EDIT_REFRESH';
const TOGGLE_SHIPPER = 'TOGGLE_SHIPPER';
const LIST = 'LIST_SHIPPERS';

export default {
  SET_SHIPPER,
  ADD_SHIPPER,
  UPDATE_SHIPPER,
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  EDIT_REFRESH,
  TOGGLE_SHIPPER,
  LIST
};
