const SET_CLIENTCONTACT = 'SET_CLIENTCONTACT';
const ADD_CLIENTCONTACT = 'ADD_CLIENTCONTACT';
const UPDATE_CLIENTCONTACT = 'ADD_CLIENTCONTACT';
const PERSIST_SUCCESS = 'PERSIST_SUCCESS_CLIENTCONTACT';
const PERSIST_ERROR = 'PERSIST_ERROR_CLIENTCONTACT';
const EDIT_REFRESH = 'EDIT_REFRESH_CLIENTCONTACT';
const LIST = 'LIST_CLIENTCONTACT';
const ERROR = 'ERROR_CLIENTCONTACT';

export default {
  SET_CLIENTCONTACT,
  ADD_CLIENTCONTACT,
  UPDATE_CLIENTCONTACT,
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  EDIT_REFRESH,
  LIST,
  ERROR
}