const PERSIST_SUCCESS = 'PERSIST_SUCCESS';
const PERSIST_ERROR = 'PERSIST_ERROR';
const LIST_JOB_ITEMS = 'LIST_JOB_ITEMS';
const ADD_JOB_ITEM = 'ADD_JOB_ITEM';
const UPDATE_JOB_ITEM = 'UPDATE_JOB_ITEM';
const DELETE_JOB_ITEM = 'DELETE_JOB_ITEM';
const ERROR = 'ERROR';

export default {
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  LIST_JOB_ITEMS,
  ADD_JOB_ITEM,
  UPDATE_JOB_ITEM,
  DELETE_JOB_ITEM,
  ERROR
};