const SET_JOB = 'SET_JOB';
const ADD_JOB = 'ADD_JOB';
const UPDATE_JOB = 'ADD_JOB';
const PERSIST_SUCCESS = 'PERSIST_SUCCESS_JOB';
const PERSIST_ERROR = 'PERSIST_ERROR_JOB';
const EDIT_REFRESH = 'EDIT_REFRESH_JOB';
const LIST = 'LIST_JOB';
const ERROR = 'ERROR_JOB';

export default {
  SET_JOB,
  ADD_JOB,
  UPDATE_JOB,
  PERSIST_SUCCESS,
  PERSIST_ERROR,
  EDIT_REFRESH,
  LIST,
  ERROR
}